# Generated by Django 5.1.7 on 2025-03-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_module_landing_url_name"),
        ("product_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="engine.module",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("module", "barcode")},
        ),
    ]
