# Generated by Django 5.1.7 on 2025-03-08 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_alter_installedmodule_installed_version_and_more"),
        ("product_module", "0002_product_module_alter_product_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default='2025-03-08T00:00:00'
),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="engine.module",
            ),
        ),
    ]
