# Generated by Django 5.1.7 on 2025-03-08 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0007_module_landing_url_name"),
        ("product_module", "0004_remove_product_created_at_alter_product_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="module",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="engine.module",
            ),
            preserve_default=False,
        ),
    ]
