# Generated by Django 5.1.7 on 2025-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_installedmodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="landing_url_name",
            field=models.CharField(
                blank=True,
                help_text="Django URL name untuk landing page modul, misal 'product_module:landing'",
                max_length=100,
                null=True,
            ),
        ),
    ]
