# Generated by Django 5.1.7 on 2025-03-08 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_alter_installedmodule_installed_version_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="landing_url_name",
        ),
    ]
