# Generated by Django 5.1.7 on 2025-03-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_remove_module_landing_url_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="landing_url_name",
            field=models.CharField(
                blank=True,
                help_text="Django URL name untuk landing page modul (contoh: 'product_module:landing')",
                max_length=100,
                null=True,
            ),
        ),
    ]
